New MDGameSynchronizer Tracking Peer ping and OS.GetTicksMsec() offset
DoubleDeez/MDFramework pull request #11
Opened 2020-06-09 15:32 UTC by Beider

Please see [this](https://github.com/DoubleDeez/MDFramework/issues/8) issue for more information about why this was added.

I will now start adding the synchronization features mentioned in [this](https://github.com/DoubleDeez/MDFramework/issues/9) issue

2020-06-09 22:25 UTC, DoubleDeez requested changes
This looks great, just a few small comments.

2020-06-09 22:25 UTC, DoubleDeez commented on MDGameInstance.cs
> +        CreateGameSynchronizer();
Can you make it so that the GameSynchronizer is opt-in? It's only necessary to create the object if the user plans on making use of it so I think it makes more sense to not create it by default as there will be some performance cost to running it.

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +public class MDGameSynchronizer : Node
Framework nodes should be marked with `[MDAutoRegister]`

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +        MDLog.Info(LOG_CAT, "Responded to server request number {0} for OS.GetTicksMsec with [{1}]", RequestNumber, OS.GetTicksMsec());
All these logs should probably be Debug or Trace

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +        GameSession = GameInstance.GetGameSession();
Add log verbosity setting:
```cs
MDLog.AddLogCategoryProperties(LOG_CAT, new MDLogProperties(MDLogLevel.Info));
```

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +    protected void ResponseTicksMsec(int PeerId, uint ClientTicksMsec, uint ServerTimeOfRequest, int RequestNumber)
Instead of trusting the Client to send their PeerId, you should use GetRPCSenderId()

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +            Timer t = new Timer();
I'd prefer full naming for variables, eg. "timer" or "pingTimer"

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +            timer.QueueFree();
Should probably Remove it too, (I have a helper extension `Node.RemoveAndFree()`)

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +    protected void PingResponse(int PeerId, uint ServerTimeOfRequest)
Same as below:

> Instead of trusting the Client to send their PeerId, you should use GetRPCSenderId()

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +        RpcId(GameSession.GetNetworkMaster(), nameof(PingResponse), MDStatics.GetPeerId(), ServerTimeOfRequest);
To save you from grabbing the server id, I have a helper: `Node.MDServerRpc` that you can use instead.

2020-06-09 22:25 UTC, DoubleDeez commented on MDNetworking/MDGameSynchronizer.cs
> +        // TODO: Improve this to remove outliers?
Could sort and ignore the highest and lowest X% of the list.

2020-06-09 22:50 UTC, Beider commented
Thanks for all the comments, almost 1 am here now so I am off to bed. I will adjust everything mentioned here and commit it along with the second part of this system which is the pause on join synchronization. I already got it working and posted a [video and logs here](https://github.com/DoubleDeez/MDFramework/issues/9) if you want to check it out.

2020-06-10 01:46 UTC, DoubleDeez commented
Adding a section to the ReadMe about the Game Synchronizer would be good too.

2020-06-10 20:15 UTC, Beider commented
Fixed the issues mentioned and finished up the synchronizer. It now comes with an example as well on how it can be used along with example GUI for the framework and synchronizer. You can see an [example video here](https://vimeo.com/427869131) of how it works. I have tried to fix so all situations of multiple players joining / leaving at the same time are taken into account.

2020-06-10 20:26 UTC, Beider commented
Well I tried to squash it all into one but ended up kind of creating a mess I think. So will just stop now and leave it as is.

2020-06-10 21:19 UTC, DoubleDeez requested changes
There's just the one typo that needs fixing and some of your .cs files are using Tabs instead of Spaces (sorry, I just want it all to be consistent)

2020-06-10 21:19 UTC, DoubleDeez commented on Examples/PredictiveSynchronizationExample/PredictiveActor.cs
> +	public static readonly string GROUP_ACTORS = "PerdictivActors";
typo: Predictive

2020-06-10 21:19 UTC, DoubleDeez commented on Examples/BasicNetworkLobby/CustomGameInstance.cs
> +        return false;
If we go with adding config files, this file could be removed

2020-06-10 21:39 UTC, Beider commented on Examples/BasicNetworkLobby/CustomGameInstance.cs
> +        return false;
I would say remove it when we do config files, at the moment starting the example on windows takes 5-10 seconds if UPNP is enabled. I will add a todo to remove it once configuration files are introduced.

2020-06-10 21:49 UTC, DoubleDeez approved these changes

2020-06-10 21:49 UTC, merged